## You should change each of the following fields
## to customize your blog

title: Big Data Guy
description: "A showcase of my work in STAT 386." 
author: Eric Antillon
author_description: "Data science major at BYU." 

url: https://ericanti.github.io
baseurl: /my-blog
header_image: "/assets/img/4204447.jpg"

## Add your social media user names.  Github is required, the rest are optional
social:
    github: ericanti
    email: ericantilloncharles@gmail.com
    linkedin: Eric Antillon



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




